//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CXP_MAESTRO {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuasarERPBanking.Resources.CXP_MAESTRO.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuentas a Pagar.
        /// </summary>
        public static string BannerCxpMaestro {
            get {
                return ResourceManager.GetString("BannerCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCiuCxpMaestro {
            get {
                return ResourceManager.GetString("errCiuCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCodCxpMaestro {
            get {
                return ResourceManager.GetString("errCodCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCondCxpMaestro {
            get {
                return ResourceManager.GetString("errCondCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCoPosCxpMaestro {
            get {
                return ResourceManager.GetString("errCoPosCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCtaMaCxpMaestro {
            get {
                return ResourceManager.GetString("errCtaMaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errDirCxpMaestro {
            get {
                return ResourceManager.GetString("errDirCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errEdoCxpMaestro {
            get {
                return ResourceManager.GetString("errEdoCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errFaxCxpMaestro {
            get {
                return ResourceManager.GetString("errFaxCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errFechCxpMaestro {
            get {
                return ResourceManager.GetString("errFechCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errFoPagCxpMaestro {
            get {
                return ResourceManager.GetString("errFoPagCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errIVACxpMaestro {
            get {
                return ResourceManager.GetString("errIVACxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errIVAranCxpMaestro {
            get {
                return ResourceManager.GetString("errIVAranCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errNCtaCxpMaestro {
            get {
                return ResourceManager.GetString("errNCtaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errNomCxpMaestro {
            get {
                return ResourceManager.GetString("errNomCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errPlazoCxpMaestro {
            get {
                return ResourceManager.GetString("errPlazoCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errRamoCxpMaestro {
            get {
                return ResourceManager.GetString("errRamoCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errRelacCxpMaestro {
            get {
                return ResourceManager.GetString("errRelacCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errReseñaCxpMaestro {
            get {
                return ResourceManager.GetString("errReseñaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errRIFCxpMaestro {
            get {
                return ResourceManager.GetString("errRIFCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errSNCCxpMaestro {
            get {
                return ResourceManager.GetString("errSNCCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errTlfCxpMaestro {
            get {
                return ResourceManager.GetString("errTlfCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errTperCxpMaestro {
            get {
                return ResourceManager.GetString("errTperCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errWebCxpMaestro {
            get {
                return ResourceManager.GetString("errWebCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetFinanciero {
            get {
                return ResourceManager.GetString("FieldsetFinanciero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetProveedor {
            get {
                return ResourceManager.GetString("FieldsetProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblBusqueda {
            get {
                return ResourceManager.GetString("lblBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a City:.
        /// </summary>
        public static string lblCiuCxpMaestro {
            get {
                return ResourceManager.GetString("lblCiuCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código:.
        /// </summary>
        public static string lblCodCxpMaestro {
            get {
                return ResourceManager.GetString("lblCodCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Condición:.
        /// </summary>
        public static string lblCondicCxpMaestro {
            get {
                return ResourceManager.GetString("lblCondicCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Postal Code:.
        /// </summary>
        public static string lblCoPosCxpMaestro {
            get {
                return ResourceManager.GetString("lblCoPosCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Major Account:.
        /// </summary>
        public static string lblCuentaCxpMaestro {
            get {
                return ResourceManager.GetString("lblCuentaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección:.
        /// </summary>
        public static string lblDirecciónCxpMaestro {
            get {
                return ResourceManager.GetString("lblDirecciónCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a State:.
        /// </summary>
        public static string lblEdoCxpMaestro {
            get {
                return ResourceManager.GetString("lblEdoCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fax:.
        /// </summary>
        public static string lblFaxCxpMaestro {
            get {
                return ResourceManager.GetString("lblFaxCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date:.
        /// </summary>
        public static string lblFechaCxpMaestro {
            get {
                return ResourceManager.GetString("lblFechaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payment Method:.
        /// </summary>
        public static string lblFoPagCxpMaestro {
            get {
                return ResourceManager.GetString("lblFoPagCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        public static string lblIMPMUNCxpMaestro {
            get {
                return ResourceManager.GetString("lblIMPMUNCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblINVNOM {
            get {
                return ResourceManager.GetString("lblINVNOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        public static string lblITFCxpMaestro {
            get {
                return ResourceManager.GetString("lblITFCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a withholding tax:.
        /// </summary>
        public static string lblIvaCxpMaestro {
            get {
                return ResourceManager.GetString("lblIvaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account Number:.
        /// </summary>
        public static string lblNCtaCxpMaestro {
            get {
                return ResourceManager.GetString("lblNCtaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        public static string lblNombreCxpMaestro {
            get {
                return ResourceManager.GetString("lblNombreCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblParam {
            get {
                return ResourceManager.GetString("lblParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a wwwwww.
        /// </summary>
        public static string lblPlazoCxpMaestro {
            get {
                return ResourceManager.GetString("lblPlazoCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a wwwwwww.
        /// </summary>
        public static string lblRamoCxpMaestro {
            get {
                return ResourceManager.GetString("lblRamoCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relation:.
        /// </summary>
        public static string lblRelacionCxpMaestro {
            get {
                return ResourceManager.GetString("lblRelacionCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Review:.
        /// </summary>
        public static string lblReseñaCxpMaestro {
            get {
                return ResourceManager.GetString("lblReseñaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a S.S.N:.
        /// </summary>
        public static string lblRifCxpMaestro {
            get {
                return ResourceManager.GetString("lblRifCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T.I.N:.
        /// </summary>
        public static string lblSncCxpMaestro {
            get {
                return ResourceManager.GetString("lblSncCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a.
        /// </summary>
        public static string lblTimbreCxpMaestro {
            get {
                return ResourceManager.GetString("lblTimbreCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone:.
        /// </summary>
        public static string lblTlfCxpMaestro {
            get {
                return ResourceManager.GetString("lblTlfCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a wwwwww.
        /// </summary>
        public static string lblTperCxpMaestro {
            get {
                return ResourceManager.GetString("lblTperCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Web:.
        /// </summary>
        public static string lblWebCxpMaestro {
            get {
                return ResourceManager.GetString("lblWebCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string liActividad {
            get {
                return ResourceManager.GetString("liActividad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string liContacto {
            get {
                return ResourceManager.GetString("liContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string liCuenta {
            get {
                return ResourceManager.GetString("liCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string msgDeleteFail {
            get {
                return ResourceManager.GetString("msgDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string msgDeleteProv {
            get {
                return ResourceManager.GetString("msgDeleteProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string placCondicion {
            get {
                return ResourceManager.GetString("placCondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --fffffffffff--.
        /// </summary>
        public static string placEdoCXP {
            get {
                return ResourceManager.GetString("placEdoCXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string placFormPago {
            get {
                return ResourceManager.GetString("placFormPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string placRamo {
            get {
                return ResourceManager.GetString("placRamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string placRelacion {
            get {
                return ResourceManager.GetString("placRelacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string placTipPersona {
            get {
                return ResourceManager.GetString("placTipPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string tittlebuttonBuscar {
            get {
                return ResourceManager.GetString("tittlebuttonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string tittlebuttonDel {
            get {
                return ResourceManager.GetString("tittlebuttonDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string tittlebuttoNew {
            get {
                return ResourceManager.GetString("tittlebuttoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string tittlebuttonSalir {
            get {
                return ResourceManager.GetString("tittlebuttonSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string tittlebuttonUp {
            get {
                return ResourceManager.GetString("tittlebuttonUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string tittleventana {
            get {
                return ResourceManager.GetString("tittleventana", resourceCulture);
            }
        }
    }
}
