//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CXP_SELECTPAGAR {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuasarERPBanking.Resources.CXP_PROCEPAGO.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string BtnImprimir {
            get {
                return ResourceManager.GetString("BtnImprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string BtnNuevo {
            get {
                return ResourceManager.GetString("BtnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string BtnPago {
            get {
                return ResourceManager.GetString("BtnPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string BtnRefrescar {
            get {
                return ResourceManager.GetString("BtnRefrescar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPFRMP {
            get {
                return ResourceManager.GetString("ErrCXPFRMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPNCTA {
            get {
                return ResourceManager.GetString("ErrCXPNCTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPRETENC {
            get {
                return ResourceManager.GetString("ErrCXPRETENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrINSTRUC {
            get {
                return ResourceManager.GetString("ErrINSTRUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRESUMENIVA {
            get {
                return ResourceManager.GetString("ErrRESUMENIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRESUMENTF {
            get {
                return ResourceManager.GetString("ErrRESUMENTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRESUMENTOTAL {
            get {
                return ResourceManager.GetString("ErrRESUMENTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRETENRSOCIAL {
            get {
                return ResourceManager.GetString("ErrRETENRSOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRETRS {
            get {
                return ResourceManager.GetString("ErrRETRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrTOTALGNERAL {
            get {
                return ResourceManager.GetString("ErrTOTALGNERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string fielFiltro {
            get {
                return ResourceManager.GetString("fielFiltro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FielPagarprove {
            get {
                return ResourceManager.GetString("FielPagarprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string fielSelecapagar {
            get {
                return ResourceManager.GetString("fielSelecapagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCONC {
            get {
                return ResourceManager.GetString("lblCONC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblcxpcod {
            get {
                return ResourceManager.GetString("lblcxpcod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPFRMP {
            get {
                return ResourceManager.GetString("lblCXPFRMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPNCTA {
            get {
                return ResourceManager.GetString("lblCXPNCTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPNOMBRE {
            get {
                return ResourceManager.GetString("lblCXPNOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPRETENC {
            get {
                return ResourceManager.GetString("lblCXPRETENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFECHDOC {
            get {
                return ResourceManager.GetString("lblFECHDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFECHVENC {
            get {
                return ResourceManager.GetString("lblFECHVENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblINSTRUC {
            get {
                return ResourceManager.GetString("lblINSTRUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMRESUMENTOTAL {
            get {
                return ResourceManager.GetString("lblMRESUMENTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMTOIMP {
            get {
                return ResourceManager.GetString("lblMTOIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNDOC {
            get {
                return ResourceManager.GetString("lblNDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPAGAR {
            get {
                return ResourceManager.GetString("lblPAGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRESUMENIVA {
            get {
                return ResourceManager.GetString("lblRESUMENIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRESUMENTF {
            get {
                return ResourceManager.GetString("lblRESUMENTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRETENRSOCIAL {
            get {
                return ResourceManager.GetString("lblRETENRSOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRETRS {
            get {
                return ResourceManager.GetString("lblRETRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblTdsProv {
            get {
                return ResourceManager.GetString("lblTdsProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblTOTAL {
            get {
                return ResourceManager.GetString("lblTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblTOTALGNERAL {
            get {
                return ResourceManager.GetString("lblTOTALGNERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblTPODOC {
            get {
                return ResourceManager.GetString("lblTPODOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string RESUMENTF {
            get {
                return ResourceManager.GetString("RESUMENTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Titulo2 {
            get {
                return ResourceManager.GetString("Titulo2", resourceCulture);
            }
        }
    }
}
