//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.COT_MAESTRO {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuasarWeb.Resources.COT_MAESTRO.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string BtnLimpiarTabla {
            get {
                return ResourceManager.GetString("BtnLimpiarTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string BtnNueva {
            get {
                return ResourceManager.GetString("BtnNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DropListOrig {
            get {
                return ResourceManager.GetString("DropListOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCC_COD {
            get {
                return ResourceManager.GetString("ErrCC_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCC_NOMB {
            get {
                return ResourceManager.GetString("ErrCC_NOMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCiuCxpMaestro {
            get {
                return ResourceManager.GetString("ErrCiuCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCondCxpMaestro {
            get {
                return ResourceManager.GetString("ErrCondCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotAdq {
            get {
                return ResourceManager.GetString("ErrCotAdq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotCc {
            get {
                return ResourceManager.GetString("ErrCotCc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotCodelab {
            get {
                return ResourceManager.GetString("ErrCotCodelab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotElafecha {
            get {
                return ResourceManager.GetString("ErrCotElafecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotElapersona {
            get {
                return ResourceManager.GetString("ErrCotElapersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotEmision {
            get {
                return ResourceManager.GetString("ErrCotEmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotFpago {
            get {
                return ResourceManager.GetString("ErrCotFpago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotGarantia {
            get {
                return ResourceManager.GetString("ErrCotGarantia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotIva {
            get {
                return ResourceManager.GetString("ErrCotIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotLugar {
            get {
                return ResourceManager.GetString("ErrCotLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotMoneda {
            get {
                return ResourceManager.GetString("ErrCotMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotNpr {
            get {
                return ResourceManager.GetString("ErrCotNpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotObserv {
            get {
                return ResourceManager.GetString("ErrCotObserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotPartida {
            get {
                return ResourceManager.GetString("ErrCotPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotPlazo {
            get {
                return ResourceManager.GetString("ErrCotPlazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotProvcod {
            get {
                return ResourceManager.GetString("ErrCotProvcod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotProvcontacto {
            get {
                return ResourceManager.GetString("ErrCotProvcontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotProy {
            get {
                return ResourceManager.GetString("ErrCotProy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotSolic {
            get {
                return ResourceManager.GetString("ErrCotSolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotSolicd {
            get {
                return ResourceManager.GetString("ErrCotSolicd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotStatus {
            get {
                return ResourceManager.GetString("ErrCotStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotSubtotal {
            get {
                return ResourceManager.GetString("ErrCotSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotTabla {
            get {
                return ResourceManager.GetString("ErrCotTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotTotal {
            get {
                return ResourceManager.GetString("ErrCotTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotTponegoc {
            get {
                return ResourceManager.GetString("ErrCotTponegoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCOTTRANSFECHARECIBE {
            get {
                return ResourceManager.GetString("errCOTTRANSFECHARECIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCOTTRANSORI {
            get {
                return ResourceManager.GetString("errCOTTRANSORI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCotVp {
            get {
                return ResourceManager.GetString("ErrCotVp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPCOD {
            get {
                return ResourceManager.GetString("ErrCXPCOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCXPCONTNOerrCXPCONTNOM {
            get {
                return ResourceManager.GetString("errCXPCONTNOerrCXPCONTNOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCXPDIR {
            get {
                return ResourceManager.GetString("errCXPDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCXPFAX {
            get {
                return ResourceManager.GetString("errCXPFAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPNOMBRE {
            get {
                return ResourceManager.GetString("ErrCXPNOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCXPRIF {
            get {
                return ResourceManager.GetString("errCXPRIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errCXPTELF {
            get {
                return ResourceManager.GetString("errCXPTELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errDET_CC {
            get {
                return ResourceManager.GetString("errDET_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errDET_PROY {
            get {
                return ResourceManager.GetString("errDET_PROY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errPRE_DEF {
            get {
                return ResourceManager.GetString("errPRE_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string errPRONOMBRE {
            get {
                return ResourceManager.GetString("errPRONOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRamoCxpMaestro {
            get {
                return ResourceManager.GetString("ErrRamoCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrReseñaCxpMaestro {
            get {
                return ResourceManager.GetString("ErrReseñaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Errtlfcxpcontcod {
            get {
                return ResourceManager.GetString("Errtlfcxpcontcod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetAprob {
            get {
                return ResourceManager.GetString("FieldsetAprob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string fieldsetCondicEntr {
            get {
                return ResourceManager.GetString("fieldsetCondicEntr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetDesc {
            get {
                return ResourceManager.GetString("FieldsetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetElab {
            get {
                return ResourceManager.GetString("FieldsetElab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetProvee {
            get {
                return ResourceManager.GetString("FieldsetProvee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetProveeAsig {
            get {
                return ResourceManager.GetString("FieldsetProveeAsig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetRev {
            get {
                return ResourceManager.GetString("FieldsetRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetSelecTipProd {
            get {
                return ResourceManager.GetString("FieldsetSelecTipProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetTotal {
            get {
                return ResourceManager.GetString("FieldsetTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblActivoFijo {
            get {
                return ResourceManager.GetString("lblActivoFijo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblASolicitar {
            get {
                return ResourceManager.GetString("lblASolicitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCC_COD {
            get {
                return ResourceManager.GetString("lblCC_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCC_NOMB {
            get {
                return ResourceManager.GetString("lblCC_NOMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCiuCxpMaestro {
            get {
                return ResourceManager.GetString("lblCiuCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCondicCxpMaestro {
            get {
                return ResourceManager.GetString("lblCondicCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotAdq {
            get {
                return ResourceManager.GetString("lblCotAdq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotCc {
            get {
                return ResourceManager.GetString("lblCotCc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotCodelab {
            get {
                return ResourceManager.GetString("lblCotCodelab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotElabFecha {
            get {
                return ResourceManager.GetString("lblCotElabFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotElapersona {
            get {
                return ResourceManager.GetString("lblCotElapersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotEmision {
            get {
                return ResourceManager.GetString("lblCotEmision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotEmision1 {
            get {
                return ResourceManager.GetString("lblCotEmision1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotFpago {
            get {
                return ResourceManager.GetString("lblCotFpago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotGarantia {
            get {
                return ResourceManager.GetString("lblCotGarantia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotIva {
            get {
                return ResourceManager.GetString("lblCotIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotLugar {
            get {
                return ResourceManager.GetString("lblCotLugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotMoneda {
            get {
                return ResourceManager.GetString("lblCotMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotNpr {
            get {
                return ResourceManager.GetString("lblCotNpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotObserv {
            get {
                return ResourceManager.GetString("lblCotObserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotPartida {
            get {
                return ResourceManager.GetString("lblCotPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotPlazo {
            get {
                return ResourceManager.GetString("lblCotPlazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotProvcod {
            get {
                return ResourceManager.GetString("lblCotProvcod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblcotprovcod1 {
            get {
                return ResourceManager.GetString("lblcotprovcod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotProvcontacto {
            get {
                return ResourceManager.GetString("lblCotProvcontacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotProy {
            get {
                return ResourceManager.GetString("lblCotProy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotSolic {
            get {
                return ResourceManager.GetString("lblCotSolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotSolicd {
            get {
                return ResourceManager.GetString("lblCotSolicd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotStatus {
            get {
                return ResourceManager.GetString("lblCotStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotSubtotal {
            get {
                return ResourceManager.GetString("lblCotSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotTabla {
            get {
                return ResourceManager.GetString("lblCotTabla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotTipAdqui {
            get {
                return ResourceManager.GetString("lblCotTipAdqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotTotal {
            get {
                return ResourceManager.GetString("lblCotTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotTponegoc {
            get {
                return ResourceManager.GetString("lblCotTponegoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotTransCantOrden {
            get {
                return ResourceManager.GetString("lblCotTransCantOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCOTTRANSFECHARECIBE {
            get {
                return ResourceManager.GetString("lblCOTTRANSFECHARECIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCOTTRANSORI {
            get {
                return ResourceManager.GetString("lblCOTTRANSORI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotTransTipo {
            get {
                return ResourceManager.GetString("lblCotTransTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCotVp {
            get {
                return ResourceManager.GetString("lblCotVp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPCOD {
            get {
                return ResourceManager.GetString("lblCXPCOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblcxpcontcod {
            get {
                return ResourceManager.GetString("lblcxpcontcod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPCONTNOM {
            get {
                return ResourceManager.GetString("lblCXPCONTNOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPDIR {
            get {
                return ResourceManager.GetString("lblCXPDIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPFAX {
            get {
                return ResourceManager.GetString("lblCXPFAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPNOMBRE {
            get {
                return ResourceManager.GetString("lblCXPNOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPRIF {
            get {
                return ResourceManager.GetString("lblCXPRIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPTELF {
            get {
                return ResourceManager.GetString("lblCXPTELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblDesc {
            get {
                return ResourceManager.GetString("lblDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblDET_CC {
            get {
                return ResourceManager.GetString("lblDET_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblDET_PROY {
            get {
                return ResourceManager.GetString("lblDET_PROY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblfech {
            get {
                return ResourceManager.GetString("lblfech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFechEmi {
            get {
                return ResourceManager.GetString("lblFechEmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblGlobal {
            get {
                return ResourceManager.GetString("lblGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblInventario {
            get {
                return ResourceManager.GetString("lblInventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblItem {
            get {
                return ResourceManager.GetString("lblItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblIva {
            get {
                return ResourceManager.GetString("lblIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNlicitacion {
            get {
                return ResourceManager.GetString("lblNlicitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPersona {
            get {
                return ResourceManager.GetString("lblPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPorc {
            get {
                return ResourceManager.GetString("lblPorc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPRE_DEF {
            get {
                return ResourceManager.GetString("lblPRE_DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPRONOMBRE {
            get {
                return ResourceManager.GetString("lblPRONOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRamoCxpMaestro {
            get {
                return ResourceManager.GetString("lblRamoCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblReseñaCxpMaestro {
            get {
                return ResourceManager.GetString("lblReseñaCxpMaestro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblServicios {
            get {
                return ResourceManager.GetString("lblServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblSubTotal {
            get {
                return ResourceManager.GetString("lblSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string liCondiciones {
            get {
                return ResourceManager.GetString("liCondiciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string liObservaciones {
            get {
                return ResourceManager.GetString("liObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string liPresupuesto {
            get {
                return ResourceManager.GetString("liPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string liProveedores {
            get {
                return ResourceManager.GetString("liProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string liWorkFlow {
            get {
                return ResourceManager.GetString("liWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string TablaProducto {
            get {
                return ResourceManager.GetString("TablaProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thCant {
            get {
                return ResourceManager.GetString("thCant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thCiudad {
            get {
                return ResourceManager.GetString("thCiudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thCodigo {
            get {
                return ResourceManager.GetString("thCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thCodProv {
            get {
                return ResourceManager.GetString("thCodProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thCondicion {
            get {
                return ResourceManager.GetString("thCondicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thContacto {
            get {
                return ResourceManager.GetString("thContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thDescripción {
            get {
                return ResourceManager.GetString("thDescripción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thEmail {
            get {
                return ResourceManager.GetString("thEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thFecha {
            get {
                return ResourceManager.GetString("thFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thIva {
            get {
                return ResourceManager.GetString("thIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thMontoTotal {
            get {
                return ResourceManager.GetString("thMontoTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thMontoUnitario {
            get {
                return ResourceManager.GetString("thMontoUnitario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thNombre {
            get {
                return ResourceManager.GetString("thNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thNombreContac {
            get {
                return ResourceManager.GetString("thNombreContac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thPorc {
            get {
                return ResourceManager.GetString("thPorc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thRamo {
            get {
                return ResourceManager.GetString("thRamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thReseña {
            get {
                return ResourceManager.GetString("thReseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thSelec {
            get {
                return ResourceManager.GetString("thSelec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thSubTotal {
            get {
                return ResourceManager.GetString("thSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thTipo {
            get {
                return ResourceManager.GetString("thTipo", resourceCulture);
            }
        }
    }
}
