//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CXP_INGREDOC {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuasarERPBanking.Resources.CXP_INGREDOC.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btnAceptar {
            get {
                return ResourceManager.GetString("btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btndoc {
            get {
                return ResourceManager.GetString("btndoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btnEliminar {
            get {
                return ResourceManager.GetString("btnEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btnIncluir {
            get {
                return ResourceManager.GetString("btnIncluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btnLimpiar {
            get {
                return ResourceManager.GetString("btnLimpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btnRevisar {
            get {
                return ResourceManager.GetString("btnRevisar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btnSalir {
            get {
                return ResourceManager.GetString("btnSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string divDistImpu {
            get {
                return ResourceManager.GetString("divDistImpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrANTICIPO {
            get {
                return ResourceManager.GetString("ErrANTICIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrAPROB {
            get {
                return ResourceManager.GetString("ErrAPROB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrBAIMP {
            get {
                return ResourceManager.GetString("ErrBAIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCC_COD {
            get {
                return ResourceManager.GetString("ErrCC_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCODTPO {
            get {
                return ResourceManager.GetString("ErrCODTPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCOMP {
            get {
                return ResourceManager.GetString("ErrCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCONC {
            get {
                return ResourceManager.GetString("ErrCONC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCTA {
            get {
                return ResourceManager.GetString("ErrCTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPCC {
            get {
                return ResourceManager.GetString("ErrCXPCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPCOD {
            get {
                return ResourceManager.GetString("ErrCXPCOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPCODALT {
            get {
                return ResourceManager.GetString("ErrCXPCODALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPPROY {
            get {
                return ResourceManager.GetString("ErrCXPPROY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPVP {
            get {
                return ResourceManager.GetString("ErrCXPVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrDES {
            get {
                return ResourceManager.GetString("ErrDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFECHDOC {
            get {
                return ResourceManager.GetString("ErrFECHDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFECHPERIODO {
            get {
                return ResourceManager.GetString("ErrFECHPERIODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFECHVENC {
            get {
                return ResourceManager.GetString("ErrFECHVENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrMTOIMP {
            get {
                return ResourceManager.GetString("ErrMTOIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNCTRL {
            get {
                return ResourceManager.GetString("ErrNCTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNDOC {
            get {
                return ResourceManager.GetString("ErrNDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNDOC2 {
            get {
                return ResourceManager.GetString("ErrNDOC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNDOC3 {
            get {
                return ResourceManager.GetString("ErrNDOC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNFILA {
            get {
                return ResourceManager.GetString("ErrNFILA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrORIGCOD {
            get {
                return ResourceManager.GetString("ErrORIGCOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrPLAZO {
            get {
                return ResourceManager.GetString("ErrPLAZO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrPORC {
            get {
                return ResourceManager.GetString("ErrPORC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrREF {
            get {
                return ResourceManager.GetString("ErrREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrSUBT {
            get {
                return ResourceManager.GetString("ErrSUBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrSUBTOTAL {
            get {
                return ResourceManager.GetString("ErrSUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrTOTAL {
            get {
                return ResourceManager.GetString("ErrTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrTPODOC {
            get {
                return ResourceManager.GetString("ErrTPODOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrUSUARIO {
            get {
                return ResourceManager.GetString("ErrUSUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string fieldsetDetDoc {
            get {
                return ResourceManager.GetString("fieldsetDetDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string fieldsetdgfac {
            get {
                return ResourceManager.GetString("fieldsetdgfac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string fieldsetImpues {
            get {
                return ResourceManager.GetString("fieldsetImpues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string fieldsetTotDoc {
            get {
                return ResourceManager.GetString("fieldsetTotDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblANTICIPO {
            get {
                return ResourceManager.GetString("lblANTICIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblAPROB {
            get {
                return ResourceManager.GetString("lblAPROB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblBAIMP {
            get {
                return ResourceManager.GetString("lblBAIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCC_COD {
            get {
                return ResourceManager.GetString("lblCC_COD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCODTPO {
            get {
                return ResourceManager.GetString("lblCODTPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCOMP {
            get {
                return ResourceManager.GetString("lblCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCONC {
            get {
                return ResourceManager.GetString("lblCONC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCTA {
            get {
                return ResourceManager.GetString("lblCTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCuenCon {
            get {
                return ResourceManager.GetString("lblCuenCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCuenCost {
            get {
                return ResourceManager.GetString("lblCuenCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCuentPagar {
            get {
                return ResourceManager.GetString("lblCuentPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCuentPagarAlt {
            get {
                return ResourceManager.GetString("lblCuentPagarAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPCC {
            get {
                return ResourceManager.GetString("lblCXPCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPCOD {
            get {
                return ResourceManager.GetString("lblCXPCOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPCODALT {
            get {
                return ResourceManager.GetString("lblCXPCODALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPPROY {
            get {
                return ResourceManager.GetString("lblCXPPROY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPVP {
            get {
                return ResourceManager.GetString("lblCXPVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblDES {
            get {
                return ResourceManager.GetString("lblDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lbldescrip {
            get {
                return ResourceManager.GetString("lbldescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFECHDOC {
            get {
                return ResourceManager.GetString("lblFECHDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFECHPERIODO {
            get {
                return ResourceManager.GetString("lblFECHPERIODO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFECHVENC {
            get {
                return ResourceManager.GetString("lblFECHVENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblImpues {
            get {
                return ResourceManager.GetString("lblImpues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMRDoc {
            get {
                return ResourceManager.GetString("lblMRDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMTOIMP {
            get {
                return ResourceManager.GetString("lblMTOIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNCTRL {
            get {
                return ResourceManager.GetString("lblNCTRL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNDOC {
            get {
                return ResourceManager.GetString("lblNDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNFILA {
            get {
                return ResourceManager.GetString("lblNFILA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblORIGCOD {
            get {
                return ResourceManager.GetString("lblORIGCOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblperiod {
            get {
                return ResourceManager.GetString("lblperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPLAZO {
            get {
                return ResourceManager.GetString("lblPLAZO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPORC {
            get {
                return ResourceManager.GetString("lblPORC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblREF {
            get {
                return ResourceManager.GetString("lblREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblSUBT {
            get {
                return ResourceManager.GetString("lblSUBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblSubTal {
            get {
                return ResourceManager.GetString("lblSubTal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblSUBTOTAL {
            get {
                return ResourceManager.GetString("lblSUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblTOTAL {
            get {
                return ResourceManager.GetString("lblTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblTPODOC {
            get {
                return ResourceManager.GetString("lblTPODOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblUSUARIO {
            get {
                return ResourceManager.GetString("lblUSUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lengtNdoc {
            get {
                return ResourceManager.GetString("lengtNdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lipre {
            get {
                return ResourceManager.GetString("lipre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string litdoc {
            get {
                return ResourceManager.GetString("litdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string placCodProve {
            get {
                return ResourceManager.GetString("placCodProve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thAsignar {
            get {
                return ResourceManager.GetString("thAsignar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thCuenCon {
            get {
                return ResourceManager.GetString("thCuenCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thCuenCost {
            get {
                return ResourceManager.GetString("thCuenCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thdescrip {
            get {
                return ResourceManager.GetString("thdescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thImpu {
            get {
                return ResourceManager.GetString("thImpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thMontImpu {
            get {
                return ResourceManager.GetString("thMontImpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thMontImpuesto {
            get {
                return ResourceManager.GetString("thMontImpuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thNombImp {
            get {
                return ResourceManager.GetString("thNombImp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thperiod {
            get {
                return ResourceManager.GetString("thperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thSubTal {
            get {
                return ResourceManager.GetString("thSubTal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thTasa {
            get {
                return ResourceManager.GetString("thTasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thTipoImp {
            get {
                return ResourceManager.GetString("thTipoImp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thTotal {
            get {
                return ResourceManager.GetString("thTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
    }
}
