//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.AF_ASIGNA {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuasarFPMWeb.Resources.AF_ASIGNA.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo Fijo.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string BarrTittle {
            get {
                return ResourceManager.GetString("BarrTittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string BtnBuscSerial {
            get {
                return ResourceManager.GetString("BtnBuscSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrAlicuota {
            get {
                return ResourceManager.GetString("ErrAlicuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCantidad {
            get {
                return ResourceManager.GetString("ErrCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCenCos {
            get {
                return ResourceManager.GetString("ErrCenCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCod {
            get {
                return ResourceManager.GetString("ErrCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCodProv {
            get {
                return ResourceManager.GetString("ErrCodProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCostUni {
            get {
                return ResourceManager.GetString("ErrCostUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCueDep {
            get {
                return ResourceManager.GetString("ErrCueDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCuenAct {
            get {
                return ResourceManager.GetString("ErrCuenAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrDepAcum {
            get {
                return ResourceManager.GetString("ErrDepAcum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrDeprec {
            get {
                return ResourceManager.GetString("ErrDeprec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrEmpl {
            get {
                return ResourceManager.GetString("ErrEmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFecAdq {
            get {
                return ResourceManager.GetString("ErrFecAdq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFech {
            get {
                return ResourceManager.GetString("ErrFech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFechAsig {
            get {
                return ResourceManager.GetString("ErrFechAsig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFechCal {
            get {
                return ResourceManager.GetString("ErrFechCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFecIni {
            get {
                return ResourceManager.GetString("ErrFecIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFecUlt {
            get {
                return ResourceManager.GetString("ErrFecUlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrGasDep {
            get {
                return ResourceManager.GetString("ErrGasDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrMarca {
            get {
                return ResourceManager.GetString("ErrMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrMesDep {
            get {
                return ResourceManager.GetString("ErrMesDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrMeYaDep {
            get {
                return ResourceManager.GetString("ErrMeYaDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrModelo {
            get {
                return ResourceManager.GetString("ErrModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNomMod {
            get {
                return ResourceManager.GetString("ErrNomMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNumAct {
            get {
                return ResourceManager.GetString("ErrNumAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNumCom {
            get {
                return ResourceManager.GetString("ErrNumCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNumFac {
            get {
                return ResourceManager.GetString("ErrNumFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrOrdCom {
            get {
                return ResourceManager.GetString("ErrOrdCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrPertA {
            get {
                return ResourceManager.GetString("ErrPertA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrSerial {
            get {
                return ResourceManager.GetString("ErrSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrStatus {
            get {
                return ResourceManager.GetString("ErrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrUbic {
            get {
                return ResourceManager.GetString("ErrUbic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrUsAsig {
            get {
                return ResourceManager.GetString("ErrUsAsig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrValor {
            get {
                return ResourceManager.GetString("ErrValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrValorLib {
            get {
                return ResourceManager.GetString("ErrValorLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrValorOrig {
            get {
                return ResourceManager.GetString("ErrValorOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrValorRes {
            get {
                return ResourceManager.GetString("ErrValorRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetCtaCon {
            get {
                return ResourceManager.GetString("FieldsetCtaCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetDAct {
            get {
                return ResourceManager.GetString("FieldsetDAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetDatAdqu {
            get {
                return ResourceManager.GetString("FieldsetDatAdqu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetDatAsig {
            get {
                return ResourceManager.GetString("FieldsetDatAsig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetDatDepr {
            get {
                return ResourceManager.GetString("FieldsetDatDepr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetMontAct {
            get {
                return ResourceManager.GetString("FieldsetMontAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FieldsetPrAso {
            get {
                return ResourceManager.GetString("FieldsetPrAso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblAlicuota {
            get {
                return ResourceManager.GetString("lblAlicuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCantidad {
            get {
                return ResourceManager.GetString("lblCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCenCos {
            get {
                return ResourceManager.GetString("lblCenCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCod {
            get {
                return ResourceManager.GetString("lblCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCodProv {
            get {
                return ResourceManager.GetString("lblCodProv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCostUni {
            get {
                return ResourceManager.GetString("lblCostUni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCueDep {
            get {
                return ResourceManager.GetString("lblCueDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCuenAct {
            get {
                return ResourceManager.GetString("lblCuenAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblDepAcum {
            get {
                return ResourceManager.GetString("lblDepAcum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblDeprec {
            get {
                return ResourceManager.GetString("lblDeprec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblEmpl {
            get {
                return ResourceManager.GetString("lblEmpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFecAdq {
            get {
                return ResourceManager.GetString("lblFecAdq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFecha {
            get {
                return ResourceManager.GetString("lblFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFechAsig {
            get {
                return ResourceManager.GetString("lblFechAsig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFechCal {
            get {
                return ResourceManager.GetString("lblFechCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFecIni {
            get {
                return ResourceManager.GetString("lblFecIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFecUlt {
            get {
                return ResourceManager.GetString("lblFecUlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblGasDep {
            get {
                return ResourceManager.GetString("lblGasDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMarca {
            get {
                return ResourceManager.GetString("lblMarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMejora {
            get {
                return ResourceManager.GetString("lblMejora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMesDep {
            get {
                return ResourceManager.GetString("lblMesDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMeYaDep {
            get {
                return ResourceManager.GetString("lblMeYaDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblModelo {
            get {
                return ResourceManager.GetString("lblModelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNomMod {
            get {
                return ResourceManager.GetString("lblNomMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNumAct {
            get {
                return ResourceManager.GetString("lblNumAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNumCom {
            get {
                return ResourceManager.GetString("lblNumCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNumFac {
            get {
                return ResourceManager.GetString("lblNumFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblOrdCom {
            get {
                return ResourceManager.GetString("lblOrdCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPertA {
            get {
                return ResourceManager.GetString("lblPertA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblPVP {
            get {
                return ResourceManager.GetString("lblPVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRest {
            get {
                return ResourceManager.GetString("lblRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblSerial {
            get {
                return ResourceManager.GetString("lblSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblUbic {
            get {
                return ResourceManager.GetString("lblUbic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblUsAsig {
            get {
                return ResourceManager.GetString("lblUsAsig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblValor {
            get {
                return ResourceManager.GetString("lblValor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblValorLib {
            get {
                return ResourceManager.GetString("lblValorLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblValorOrig {
            get {
                return ResourceManager.GetString("lblValorOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblValorRes {
            get {
                return ResourceManager.GetString("lblValorRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string msgCamVaci {
            get {
                return ResourceManager.GetString("msgCamVaci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string msgCantMay {
            get {
                return ResourceManager.GetString("msgCantMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string msgCantMen {
            get {
                return ResourceManager.GetString("msgCantMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string msgConfDel {
            get {
                return ResourceManager.GetString("msgConfDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string msgFaltCod {
            get {
                return ResourceManager.GetString("msgFaltCod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string msgIntCant {
            get {
                return ResourceManager.GetString("msgIntCant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string PlacCCosto {
            get {
                return ResourceManager.GetString("PlacCCosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string PlacProve {
            get {
                return ResourceManager.GetString("PlacProve", resourceCulture);
            }
        }
    }
}
