//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.CXP_ORDPAGO {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuasarERPBanking.Resources.CXP_ORDPAGO.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btnImpr {
            get {
                return ResourceManager.GetString("btnImpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btnNuevo {
            get {
                return ResourceManager.GetString("btnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string btnProce {
            get {
                return ResourceManager.GetString("btnProce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrABONO {
            get {
                return ResourceManager.GetString("ErrABONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrACTPORC {
            get {
                return ResourceManager.GetString("ErrACTPORC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrAPROB {
            get {
                return ResourceManager.GetString("ErrAPROB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrBANCO {
            get {
                return ResourceManager.GetString("ErrBANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrBENEF {
            get {
                return ResourceManager.GetString("ErrBENEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCONC {
            get {
                return ResourceManager.GetString("ErrCONC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCTA_ABO {
            get {
                return ResourceManager.GetString("ErrCTA_ABO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPCOD {
            get {
                return ResourceManager.GetString("ErrCXPCOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPFRMP {
            get {
                return ResourceManager.GetString("ErrCXPFRMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPNCTA {
            get {
                return ResourceManager.GetString("ErrCXPNCTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPNOMBRE {
            get {
                return ResourceManager.GetString("ErrCXPNOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPRETENC {
            get {
                return ResourceManager.GetString("ErrCXPRETENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrCXPTIMBRE {
            get {
                return ResourceManager.GetString("ErrCXPTIMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrDESCRIPCION {
            get {
                return ResourceManager.GetString("ErrDESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFECHA {
            get {
                return ResourceManager.GetString("ErrFECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFECHDOC {
            get {
                return ResourceManager.GetString("ErrFECHDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFECHVENC {
            get {
                return ResourceManager.GetString("ErrFECHVENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrFRMPAGO {
            get {
                return ResourceManager.GetString("ErrFRMPAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrINSTR {
            get {
                return ResourceManager.GetString("ErrINSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrMONTO {
            get {
                return ResourceManager.GetString("ErrMONTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrMONTOISLR {
            get {
                return ResourceManager.GetString("ErrMONTOISLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrMONTORET {
            get {
                return ResourceManager.GetString("ErrMONTORET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrMTOIMP {
            get {
                return ResourceManager.GetString("ErrMTOIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNDOC {
            get {
                return ResourceManager.GetString("ErrNDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNROCOMP {
            get {
                return ResourceManager.GetString("ErrNROCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNROID {
            get {
                return ResourceManager.GetString("ErrNROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNROORDEN {
            get {
                return ResourceManager.GetString("ErrNROORDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrNUMERO {
            get {
                return ResourceManager.GetString("ErrNUMERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrREF {
            get {
                return ResourceManager.GetString("ErrREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRESUMENTF {
            get {
                return ResourceManager.GetString("ErrRESUMENTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRESUMENTOTAL {
            get {
                return ResourceManager.GetString("ErrRESUMENTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRETIVA {
            get {
                return ResourceManager.GetString("ErrRETIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrRETRS {
            get {
                return ResourceManager.GetString("ErrRETRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrSTATUS {
            get {
                return ResourceManager.GetString("ErrSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrSUBT {
            get {
                return ResourceManager.GetString("ErrSUBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrTIMBREFISCAL {
            get {
                return ResourceManager.GetString("ErrTIMBREFISCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrTOTAL {
            get {
                return ResourceManager.GetString("ErrTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string ErrUSUARIO {
            get {
                return ResourceManager.GetString("ErrUSUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string FielRetBusUsua {
            get {
                return ResourceManager.GetString("FielRetBusUsua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblABONO {
            get {
                return ResourceManager.GetString("lblABONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblACTPORC {
            get {
                return ResourceManager.GetString("lblACTPORC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblAPROB {
            get {
                return ResourceManager.GetString("lblAPROB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblBANCO {
            get {
                return ResourceManager.GetString("lblBANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblBENEF {
            get {
                return ResourceManager.GetString("lblBENEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblComp {
            get {
                return ResourceManager.GetString("lblComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCONC {
            get {
                return ResourceManager.GetString("lblCONC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCTA_ABO {
            get {
                return ResourceManager.GetString("lblCTA_ABO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPCOD {
            get {
                return ResourceManager.GetString("lblCXPCOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPFRMP {
            get {
                return ResourceManager.GetString("lblCXPFRMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPNCTA {
            get {
                return ResourceManager.GetString("lblCXPNCTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPNOMBRE {
            get {
                return ResourceManager.GetString("lblCXPNOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPRETENC {
            get {
                return ResourceManager.GetString("lblCXPRETENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblCXPTIMBRE {
            get {
                return ResourceManager.GetString("lblCXPTIMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblDESCRIPCION {
            get {
                return ResourceManager.GetString("lblDESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFECHA {
            get {
                return ResourceManager.GetString("lblFECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFECHDOC {
            get {
                return ResourceManager.GetString("lblFECHDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFECHVENC {
            get {
                return ResourceManager.GetString("lblFECHVENC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblFRMPAGO {
            get {
                return ResourceManager.GetString("lblFRMPAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblINSTR {
            get {
                return ResourceManager.GetString("lblINSTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMONTO {
            get {
                return ResourceManager.GetString("lblMONTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMONTOISLR {
            get {
                return ResourceManager.GetString("lblMONTOISLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMONTORET {
            get {
                return ResourceManager.GetString("lblMONTORET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMtnPag {
            get {
                return ResourceManager.GetString("lblMtnPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblMTOIMP {
            get {
                return ResourceManager.GetString("lblMTOIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNDOC {
            get {
                return ResourceManager.GetString("lblNDOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNROCOMP {
            get {
                return ResourceManager.GetString("lblNROCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNROID {
            get {
                return ResourceManager.GetString("lblNROID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNROORDEN {
            get {
                return ResourceManager.GetString("lblNROORDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblNUMERO {
            get {
                return ResourceManager.GetString("lblNUMERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblOrdPago {
            get {
                return ResourceManager.GetString("lblOrdPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblOrdPgoComp {
            get {
                return ResourceManager.GetString("lblOrdPgoComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblREF {
            get {
                return ResourceManager.GetString("lblREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRESUMENIVA {
            get {
                return ResourceManager.GetString("lblRESUMENIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRESUMENTF {
            get {
                return ResourceManager.GetString("lblRESUMENTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRETIVA {
            get {
                return ResourceManager.GetString("lblRETIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRETRS {
            get {
                return ResourceManager.GetString("lblRETRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblRSMENTOTAL {
            get {
                return ResourceManager.GetString("lblRSMENTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblSTATUS {
            get {
                return ResourceManager.GetString("lblSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblSUBT {
            get {
                return ResourceManager.GetString("lblSUBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblTIMBREFISCAL {
            get {
                return ResourceManager.GetString("lblTIMBREFISCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblTOTAL {
            get {
                return ResourceManager.GetString("lblTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lblUSUARIO {
            get {
                return ResourceManager.GetString("lblUSUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string sbtltDetDocSel {
            get {
                return ResourceManager.GetString("sbtltDetDocSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string sbtltFrmPgo {
            get {
                return ResourceManager.GetString("sbtltFrmPgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thAprob {
            get {
                return ResourceManager.GetString("thAprob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thBanco {
            get {
                return ResourceManager.GetString("thBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thBenef {
            get {
                return ResourceManager.GetString("thBenef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thCntaPagar {
            get {
                return ResourceManager.GetString("thCntaPagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thConc {
            get {
                return ResourceManager.GetString("thConc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thCtaCont {
            get {
                return ResourceManager.GetString("thCtaCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thElim {
            get {
                return ResourceManager.GetString("thElim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thFech {
            get {
                return ResourceManager.GetString("thFech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thFechDoc {
            get {
                return ResourceManager.GetString("thFechDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thFrmPgo {
            get {
                return ResourceManager.GetString("thFrmPgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thInstruc {
            get {
                return ResourceManager.GetString("thInstruc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thMnto {
            get {
                return ResourceManager.GetString("thMnto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thMonto {
            get {
                return ResourceManager.GetString("thMonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thNdoc {
            get {
                return ResourceManager.GetString("thNdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thNroPago {
            get {
                return ResourceManager.GetString("thNroPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thNum {
            get {
                return ResourceManager.GetString("thNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thProvee {
            get {
                return ResourceManager.GetString("thProvee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thRef {
            get {
                return ResourceManager.GetString("thRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thRetISLR {
            get {
                return ResourceManager.GetString("thRetISLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thRetIva {
            get {
                return ResourceManager.GetString("thRetIva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thTtal {
            get {
                return ResourceManager.GetString("thTtal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string thVenc {
            get {
                return ResourceManager.GetString("thVenc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string TltOrdPagoComp {
            get {
                return ResourceManager.GetString("TltOrdPagoComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string TltOrdPagoUsua {
            get {
                return ResourceManager.GetString("TltOrdPagoUsua", resourceCulture);
            }
        }
    }
}
